name: sellermultivendor
description: A new Flutter project.

publish_to: "none"
version: 2.8.0+14

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.3.1
  cached_network_image: ^3.4.1
  firebase_core: ^3.6.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  sms_autofill: ^2.3.0
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  file_picker: ^8.1.2
  sticky_headers: ^0.3.0+2
  html_editor_enhanced: ^2.5.0  # Stable version to avoid TextTheme issues
  mime: ^1.0.6
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  flutter_widget_from_html: ^0.15.3
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  flutter_email_sender: ^6.0.3
  bloc: ^8.1.4
  intl_phone_field: ^3.2.0
  open_filex: ^4.5.0
  external_path: ^2.2.0
  path_provider: ^2.1.5
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4  # Stable, existing version
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  permission_handler: ^11.4.0
  device_info_plus: ^11.1.0

dependency_overrides:
  flutter_inappwebview: ^6.1.0
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  just_audio: ^0.9.46
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/PNG/
    - assets/images/SVG/
    - assets/animation/
    - lib/Language/
    