// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3d73M7qeLvv3uTEp3Q0aG-xV9Kt91ko8',
    appId: '1:936221232681:android:ce333595f68202d1fa5638',
    messagingSenderId: '936221232681',
    projectId: 'mntom-bd9a1',
    storageBucket: 'mntom-bd9a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn73MkxubVnSTRKGIucw1OwvJbxCOFs1g',
    appId: '1:936221232681:ios:1545ab00866a5888fa5638',
    messagingSenderId: '936221232681',
    projectId: 'mntom-bd9a1',
    storageBucket: 'mntom-bd9a1.firebasestorage.app',
    androidClientId: '936221232681-1ri61bcsqp32d9q9c8t887gviia7sfhj.apps.googleusercontent.com',
    iosClientId: '936221232681-v41ovbih4l17ape9m784dljns86074p7.apps.googleusercontent.com',
    iosBundleId: 'com.mntom.seller',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IVkbSpPjC4kcC34PP6AauqNfaZa7hJ4',
    appId: '1:936221232681:web:2e6c8450411949bafa5638',
    messagingSenderId: '936221232681',
    projectId: 'mntom-bd9a1',
    authDomain: 'mntom-bd9a1.firebaseapp.com',
    storageBucket: 'mntom-bd9a1.firebasestorage.app',
    measurementId: 'G-0WSCH2LTQF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn73MkxubVnSTRKGIucw1OwvJbxCOFs1g',
    appId: '1:936221232681:ios:813d7734854ac195fa5638',
    messagingSenderId: '936221232681',
    projectId: 'mntom-bd9a1',
    storageBucket: 'mntom-bd9a1.firebasestorage.app',
    androidClientId: '936221232681-1ri61bcsqp32d9q9c8t887gviia7sfhj.apps.googleusercontent.com',
    iosClientId: '936221232681-emrelhdq2rkfj3vnvlhgeb9v92jv9b2j.apps.googleusercontent.com',
    iosBundleId: 'eshop.mt.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKQZ5wEEzZuYEnW3a3TYTSaayupWAgLl4',
    appId: '1:936221232681:web:3e9473ac1a935cb1fa5638',
    messagingSenderId: '936221232681',
    projectId: 'mntom-bd9a1',
    authDomain: 'mntom-bd9a1.firebaseapp.com',
    storageBucket: 'mntom-bd9a1.firebasestorage.app',
    measurementId: 'G-8ZGW9SW6GJ',
  );

}